#!/usr/bin/env bash
# Install nginx web server
# Listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
