#!/usr/bin/env bash
# Install nginix web server
# Listen on port 80

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index*html
service nginx start
