#!/usr/bin/env bash
# Install nginx web server
# Listen on port 80

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
