#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/goodnessjames permanent;"
sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
